### ISSUE TITLE
This doesn't work anymore.

### ISSUE THREAD

**Issue by SkyOc1** [KunoichiZ/SoVUS-NTR-Plugin#9]
since the last update of the game, this plugin no longer works.

**Comment by KunoichiZ** [comment]
Yeah I know. Delete the update if you wish to use this plugin. I no longer have the time to update the plugin.

**Comment by DrawYourSwordRamza** [comment]
Aren't you a diligent worker?

**Comment by KunoichiZ** [comment]
@DrawYourSwordRamza I don't know what your problem is. I'm in college and I don't have the time to update the plugin to support the v1.1 update. If you want this to work, fork it and fix it yourself. I don't need your sass.

**Comment by saijm4444** [comment]
@DrawYourSwordRamza , look, I don't really understand your need to post such a comment, but let me say this: There is an updated plugin for the EU 1.1 version, and @KunoichiZ made it. Get a EU Rom, put your save in there and play it if you want it updated.  Or don't update your US version. There really is nothing gamebreaking fixed in 1.1 .
